"use client"

import Link from 'next/link'
import { Button } from '@/components/button'
import { ChevronDown, ChevronUp } from 'lucide-react'
import { useState } from 'react'

export default function FAQPage() {
  const [openItems, setOpenItems] = useState<number[]>([])

  const toggleItem = (index: number) => {
    setOpenItems(prev => 
      prev.includes(index) 
        ? prev.filter(i => i !== index)
        : [...prev, index]
    )
  }

  const faqs = [
    {
      question: "What happens after the 7-day trial?",
      answer: "You can choose a paid plan (Starter or Pro) to keep your site live. If you decide not to continue, don't worry – your site will be saved (archived) for a short period so you can still retrieve your content. However, it won't remain publicly accessible unless you pick a plan."
    },
    {
      question: "Do I own the website you create?",
      answer: "Yes, absolutely. The website is 100% yours. It's a standard WordPress website under the hood, which means you can export it, back it up, or even move it to another host if you ever needed to. Our platform does the heavy lifting to create and manage it, but you're the owner."
    },
    {
      question: "Can I use my own domain name?",
      answer: "Yes, you can connect your custom domain. During the free trial, your site will be on a temporary Naveeg subdomain. Custom domains are available on the Pro plan – it's a one-click setup when you upgrade, and we'll handle the SSL certificate and configuration for you."
    },
    {
      question: "I'm not tech-savvy… can I really do this?",
      answer: "Definitely. Naveeg was built for people who have no technical background. If you can fill a short form and click a button, you can build your site with Naveeg. Everything is either automated or very clearly explained. Plus, we're here to help if you get stuck – just contact us!"
    },
    {
      question: "What if I already have a website/domain?",
      answer: "That's fine! If you have a domain, you can connect it (Pro plan) to the new Naveeg site we create for you. If you already have a website but want to switch to Naveeg for the automation and ease, we can help migrate your content. Our goal is to make your life easier, even if it means helping you move from an old setup."
    },
    {
      question: "Is the content really generated by AI? Will it be relevant to my business?",
      answer: "Our AI is quite clever! It takes the details you give (industry, business name, keywords about what you do) and searches a knowledge base to draft text and suggest images that fit. We've trained it with information about various small businesses. In the Jane's Bakery demo, for example, it wrote about fresh cupcakes and custom cakes because we told it it's a bakery. You can always tweak the content, but most users find it's a great starting point and saves them lots of time."
    },
    {
      question: "Can I edit my website after it's generated?",
      answer: "Yes, you have full control to edit and update your website. Naveeg provides an easy editor interface (and you can also use the standard WordPress editor if you're familiar with it). Change text, add pictures, create new pages – it's all possible. And if you're not comfortable doing it yourself, you can always ask us or invite a team member to help via the Team feature."
    },
    {
      question: "How do payments work for the subscription?",
      answer: "We use Stripe for secure payments. When you're ready to upgrade, you'll be taken to a Stripe checkout page to enter your payment info safely. Stripe is a trusted payment processor (used by millions of businesses). You can use any major credit/debit card. Subscriptions are billed monthly (cancel anytime), and you can also choose an annual plan for a discount (if we offer one). After payment, your site's features upgrade instantly."
    },
    {
      question: "Is Naveeg really all I need? What about social media/Google/etc.?",
      answer: "Naveeg's aim is to be your central online hub. The website we create will be the cornerstone of your online presence. We also make it easy to integrate with other channels: for example, you can embed your Instagram feed on your site, link out to your Facebook page, and connect Google Analytics to track traffic. For Google Search and Maps, just having a Naveeg site with good SEO will improve your discoverability, but we always recommend claiming your Google Business Profile too – which Naveeg can help with (on Pro plans we'll guide you through it in the dashboard). In short, Naveeg covers the website and integrations, and we'll advise you on leveraging other online channels effectively."
    },
    {
      question: "What's the difference between Starter and Pro?",
      answer: "Starter (€49/month) includes 1 website, free Naveeg subdomain, AI website builder, SEO basics, contact form, and email support. Pro (€99/month) includes up to 5 websites, custom domains, AI chatbot, advanced analytics, team collaboration, e-commerce ready, automations & integrations, and priority support."
    },
    {
      question: "Can I cancel anytime?",
      answer: "Yes, you can cancel your subscription at any time. Your sites will remain active until the end of your current billing period. No long-term contracts or cancellation fees."
    },
    {
      question: "Do you offer refunds?",
      answer: "Yes, we offer a 30-day money-back guarantee for all paid plans. If you're not satisfied with our service, contact us within 30 days for a full refund, no questions asked."
    },
    {
      question: "Is my data secure?",
      answer: "Yes, we take data security seriously. All data is stored in European data centers (GDPR compliant), we use SSL encryption everywhere, and follow industry best practices for security. We never share your data with third parties."
    },
    {
      question: "Can I get help if I need it?",
      answer: "Of course! We offer email support for all users, with priority support for paid plans. We also have a comprehensive help center with guides, tutorials, and best practices to help you succeed."
    },
    {
      question: "What payment methods do you accept?",
      answer: "We accept all major credit cards (Visa, Mastercard, American Express) and PayPal. All prices include VAT for European customers. We use Stripe for secure payment processing."
    }
  ]

  return (
    <div className="min-h-screen bg-white">
      {/* Navigation */}
      <nav className="bg-white border-b border-gray-200 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center">
              <Link href="/" className="text-2xl font-bold text-blue-600">
                Naveeg
              </Link>
            </div>
            <div className="hidden md:flex items-center space-x-8">
              <Link href="/features" className="text-gray-600 hover:text-gray-900">Features</Link>
              <Link href="/pricing" className="text-gray-600 hover:text-gray-900">Pricing</Link>
              <Link href="/about" className="text-gray-600 hover:text-gray-900">About</Link>
              <Link href="/contact" className="text-gray-600 hover:text-gray-900">Contact</Link>
            </div>
            <div className="flex items-center space-x-4">
              <Link href="https://app.naveeg.com/signin">
                <Button variant="outline">Sign In</Button>
              </Link>
              <Link href="https://app.naveeg.com/signup">
                <Button>Start Free Trial</Button>
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="py-20 bg-gradient-to-br from-blue-50 to-indigo-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            Frequently Asked Questions
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Everything you need to know about Naveeg. Can't find what you're looking for? 
            <Link href="/contact" className="text-blue-600 hover:text-blue-700 ml-1">
              Contact us
            </Link> and we'll help you out.
          </p>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="bg-white rounded-lg shadow-sm border border-gray-200">
                <button
                  onClick={() => toggleItem(index)}
                  className="w-full px-6 py-4 text-left flex justify-between items-center hover:bg-gray-50 transition-colors"
                >
                  <span className="text-lg font-semibold text-gray-900">
                    {faq.question}
                  </span>
                  {openItems.includes(index) ? (
                    <ChevronUp className="w-5 h-5 text-gray-500" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-500" />
                  )}
                </button>
                {openItems.includes(index) && (
                  <div className="px-6 pb-4">
                    <p className="text-gray-600 leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-blue-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-4xl font-bold text-white mb-4">
            Still have questions?
          </h2>
          <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
            Our support team is here to help. Get in touch and we'll get back to you within 24 hours.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/contact">
              <Button size="lg" variant="secondary">
                Contact Support
              </Button>
            </Link>
            <Link href="https://app.naveeg.com/signup">
              <Button size="lg" variant="outline" className="bg-transparent border-white text-white hover:bg-white hover:text-blue-600">
                Start Free Trial
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <h3 className="text-2xl font-bold mb-4">Naveeg</h3>
              <p className="text-gray-400">
                The easiest way to create and manage WordPress sites for European businesses.
              </p>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Product</h4>
              <ul className="space-y-2">
                <li><Link href="/features" className="text-gray-400 hover:text-white">Features</Link></li>
                <li><Link href="/pricing" className="text-gray-400 hover:text-white">Pricing</Link></li>
                <li><Link href="/templates" className="text-gray-400 hover:text-white">Templates</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Company</h4>
              <ul className="space-y-2">
                <li><Link href="/about" className="text-gray-400 hover:text-white">About</Link></li>
                <li><Link href="/contact" className="text-gray-400 hover:text-white">Contact</Link></li>
                <li><Link href="/privacy" className="text-gray-400 hover:text-white">Privacy</Link></li>
                <li><Link href="/terms" className="text-gray-400 hover:text-white">Terms</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Support</h4>
              <ul className="space-y-2">
                <li><Link href="/help" className="text-gray-400 hover:text-white">Help Center</Link></li>
                <li><Link href="/docs" className="text-gray-400 hover:text-white">Documentation</Link></li>
                <li><Link href="/status" className="text-gray-400 hover:text-white">Status</Link></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
            <p>&copy; 2024 Naveeg. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
